; Here you can store your preferred configuration for `slounik` module. For more info see README.
; The module might break if this file is populated incorrectly, so be cautious!
; Keep the original versions of the module files you want to modify.

; Paths can be absolute or relative to `slounik.py` file (and this file).

[Paths]
databasePath = ../slounik/assets/dictionary.db
exportDirectoryPath = ../exports

[StopWords]
; Stop-words are enabled only if `enableStopWords` value equals `yes`.
enableStopWords = yes
stopWordsPath = ../slounik/assets/stop_words.txt